### ISSUE TITLE
Unable to see user's details

### ISSUE THREAD

**Issue by simfer** [niralmunjariya/angular-4-demo-app#1]
Hi Niral,
I've the following problem. I can see the list of users, but when I click on the little eye icon to get user's detail, the form is not populated. It seems a problem with "ngModel". Can you understand where is the problem?
![angular](https://user-images.githubusercontent.com/6877529/28964010-5fb1ae00-790b-11e7-9695-6f6a24ef9435.png)

Simmaco

**Comment by niralmunjariya** [comment]
@simfer,
Are there any errors in the browser's console?

**Comment by simfer** [comment]
Sorry for may late response!
No errors in the console as you can see here.
![noerr](https://user-images.githubusercontent.com/6877529/29561978-d7ae57fc-8737-11e7-84e0-0deba0047f81.png)

**Comment by niralmunjariya** [comment]
@simfer,
Can you please check the API app because I'm getting the data in both view and update options.
Can you provide more information because I'm unable to replicate the issue?

**Comment by simfer** [comment]
Hi Niral,
I found the issue! It was the API returning more than one row for the users. So the JSON response was an array and not a single object.
Sorry for this inconvenience and thanks in any case for your help.
Regards,
Simmaco
